In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:/ML Internship/car_evaluation_lyst1729241367952.csv")
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [3]:
#Rename the columns
col_name=["Buying","Maintenace","Doors","Persons","Lugboot","Safety","Class"]
df.columns

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [7]:
df.columns=col_name

In [8]:
df.describe()

       Buying Maintenace Doors Persons Lugboot Safety  Class
count    1727       1727  1727    1727    1727   1727   1727
unique      4          4     4       3       3      3      4
top      high       high     3       4     med    med  unacc
freq      432        432   432     576     576    576   1209

In [15]:
#Putting the value of x and y
x=df.drop("Class",axis=1)
y=df["Class"]

In [13]:
x

     Buying Maintenace  Doors Persons Lugboot Safety
0     vhigh      vhigh      2       2   small    med
1     vhigh      vhigh      2       2   small   high
2     vhigh      vhigh      2       2     med    low
3     vhigh      vhigh      2       2     med    med
4     vhigh      vhigh      2       2     med   high
...     ...        ...    ...     ...     ...    ...
1722    low        low  5more    more     med    med
1723    low        low  5more    more     med   high
1724    low        low  5more    more     big    low
1725    low        low  5more    more     big    med
1726    low        low  5more    more     big   high

[1727 rows x 6 columns]

In [14]:
y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...
1722     good
1723    vgood
1724    unacc
1725     good
1726    vgood
Name: Class, Length: 1727, dtype: object

In [17]:
#Splitting the dataset into Training and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=37)

In [18]:
x_train

     Buying Maintenace  Doors Persons Lugboot Safety
459    high      vhigh      3       2   small    med
1526    low        med      2       4     big    low
542    high       high      2       2     med    low
1259    med        low      4    more   small    low
898     med      vhigh      3       2     big   high
...     ...        ...    ...     ...     ...    ...
437    high      vhigh      2       2     big    low
988     med       high      2       4     big   high
251   vhigh        med      3       4   small    low
844    high        low  5more       2     big   high
363   vhigh        low      3       4     med    med

[1208 rows x 6 columns]

In [19]:
y_train

459     unacc
1526    unacc
542     unacc
1259    unacc
898     unacc
        ...
437     unacc
988       acc
251     unacc
844     unacc
363     unacc
Name: Class, Length: 1208, dtype: object

In [20]:
x_test

     Buying Maintenace Doors Persons Lugboot Safety
231   vhigh        med     2       4     big    med
1450    low       high     3    more   small   high
1561    low        med     3    more     med   high
1642    low        low     2    more     med   high
1421    low       high     2    more   small    low
...     ...        ...   ...     ...     ...    ...
1407    low       high     2       2     med    med
1460    low       high     4       2     med    low
828    high        low     4    more   small    med
260   vhigh        med     3    more   small    low
1142    med        med     4       4   small    low

[519 rows x 6 columns]

In [21]:
y_test

231       acc
1450      acc
1561    vgood
1642     good
1421    unacc
        ...
1407    unacc
1460    unacc
828     unacc
260     unacc
1142    unacc
Name: Class, Length: 519, dtype: object

In [32]:
#Encoding of categorical data: Preprocessing of data
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
x_train=encoder.fit_transform(x_train)
x_test=encoder.fit_transform(x_test)

In [33]:
x_train

array([[0., 3., 1., 0., 2., 2.],
       [1., 2., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       ...,
       [3., 2., 1., 1., 2., 1.],
       [0., 1., 3., 0., 0., 0.],
       [3., 1., 1., 1., 1., 2.]], shape=(1208, 6))

In [34]:
x_test

array([[3., 2., 0., 1., 0., 2.],
       [1., 0., 1., 2., 2., 0.],
       [1., 2., 1., 2., 1., 0.],
       ...,
       [0., 1., 2., 2., 2., 2.],
       [3., 2., 1., 2., 2., 1.],
       [2., 2., 2., 1., 2., 1.]], shape=(519, 6))

In [39]:
x_train.dtype

dtype('float64')

In [41]:
#Application of model
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,random_state=77,bootstrap=True)
rfc.fit(x_train,y_train)

RandomForestClassifier(random_state=77)

In [43]:
y_pred=rfc.predict(x_test)
y_pred

array(['unacc', 'acc', 'vgood', 'good', 'unacc', 'unacc', 'unacc', 'acc',
       'acc', 'unacc', 'unacc', 'unacc', 'good', 'vgood', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'acc', 'good', 'unacc', 'unacc', 'vgood', 'unacc', 'vgood',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc', 'unacc',
       'acc', 'acc', 'unacc', 'unacc', 'good', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'good', 'unacc', 'unacc', 'unacc', 'good', 'acc', 'unacc', 'vgood',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'vgood', 'unacc', 'unacc', 'good', 'vgood', 'unacc', 'unacc',
       'unacc', 'vgood', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'good',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'good', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc',
       'acc', 'vgood', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'acc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'good', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'vgood', 'acc',
       'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'acc', 'unacc', 'acc', 'unacc', 'acc', 'acc', 'unacc', 'good',
       'acc', 'unacc', 'unacc', 'unacc', 'good', 'unacc', 'unacc', 'acc',
       'unacc', 'unacc', 'unacc', 'acc', 'vgood', 'unacc', 'unacc', 'acc',
       'acc', 'vgood', 'vgood', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'acc', 'acc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'acc',
       'good', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc',
       'unacc', 'unacc', 'unacc', 'acc', 'vgood', 'unacc', 'unacc',
       'vgood', 'acc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'unacc', 'good', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'good', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'vgood', 'acc',
       'unacc', 'unacc', 'acc', 'acc', 'vgood', 'unacc', 'acc', 'acc',
       'acc', 'acc', 'good', 'acc', 'unacc', 'acc', 'unacc', 'acc',
       'unacc', 'acc', 'vgood', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'unacc', 'acc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'vgood', 'unacc', 'unacc', 'good', 'unacc', 'unacc',
       'good', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc',
       'acc', 'unacc', 'acc', 'unacc', 'good', 'unacc', 'acc', 'acc',
       'acc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc',
       'good', 'acc', 'unacc', 'unacc', 'unacc', 'good', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'vgood',
       'unacc', 'unacc', 'unacc', 'good', 'unacc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc'], dtype=object)

In [44]:
y_test

231       acc
1450      acc
1561    vgood
1642     good
1421    unacc
        ...
1407    unacc
1460    unacc
828     unacc
260     unacc
1142    unacc
Name: Class, Length: 519, dtype: object

In [45]:
#Classification report, Accuracy score and Confusion matrix
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         acc       0.91      0.90      0.91       126
        good       0.86      0.70      0.78        27
       unacc       0.98      0.99      0.98       347
       vgood       0.95      1.00      0.97        19

    accuracy                           0.96       519
   macro avg       0.93      0.90      0.91       519
weighted avg       0.95      0.96      0.95       519

In [47]:
confusion_matrix(y_pred,y_test)

array([[114,   8,   3,   0],
       [  3,  19,   0,   0],
       [  8,   0, 344,   0],
       [  1,   0,   0,  19]])

In [49]:
#Feature Score
pd.Series(rfc.feature_importances_,index=x.columns)

Buying        0.182359
Maintenace    0.156944
Doors         0.074107
Persons       0.218266
Lugboot       0.080769
Safety        0.287556
dtype: float64