# Pandas

1. Full form: Panel Data
2. Very helpful in performing data analysis.
3. 1-D data set is known as Series.
4. 2-D data set is known as Dataframe.

In [6]:
import pandas as pd
s1=pd.Series(data=[3,7,77],index=["HS","DK","SG"])
print(s1)

HS     3
DK     7
SG    77
dtype: int64

In [7]:
s2=pd.Series(data=[10,20,30],index=["Physics","Chemistry","Maths"])
print(s2)

Physics      10
Chemistry    20
Maths        30
dtype: int64

In [10]:
d1=pd.DataFrame(data={"HS":[3,37],"DK":[7,10]})
print(d1)

   HS  DK
0   3   7
1  37  10

In [13]:
d2=pd.DataFrame(data={"HS":[3,37],"DK":[7,10]},index=["a","b"])
print(d2)

   HS  DK
a   3   7
b  37  10

In [15]:
# Both the series should have same indices
d3=pd.DataFrame(data={"col1":s1,"col2":s2})
print(d3)

           col1  col2
Chemistry   NaN  20.0
DK          7.0   NaN
HS          3.0   NaN
Maths       NaN  30.0
Physics     NaN  10.0
SG         77.0   NaN

In [23]:
df=pd.read_csv("C:/Users/Divyanshi Kesharwani/Downloads/Data.csv")
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## High Level Understanding of the Data

In [24]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [25]:
df.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [26]:
df.head(3)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [27]:
df.tail(3)

   Country   Age   Salary Purchased
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [29]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [32]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

## Low Level Understanding

In [33]:
df["Salary"]

0    72000.0
1    48000.0
2    54000.0
3    61000.0
4        NaN
5    58000.0
6    52000.0
7    79000.0
8    83000.0
9    67000.0
Name: Salary, dtype: float64

In [34]:
df["Age"].describe()

count     9.000000
mean     38.777778
std       7.693793
min      27.000000
25%      35.000000
50%      38.000000
75%      44.000000
max      50.000000
Name: Age, dtype: float64

In [36]:
df.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64